// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAySrf8DKWQIx4oULMmDLhyZK4wP3cT0EY',
    appId: '1:1081533382829:web:9b9cad8b82aff413a78624',
    messagingSenderId: '1081533382829',
    projectId: 'test-49143',
    authDomain: 'test-49143.firebaseapp.com',
    storageBucket: 'test-49143.firebasestorage.app',
    measurementId: 'G-8PCWVTQSPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_aU9kmCV3qJKAIMiAvlwKkM7msSFWahg',
    appId: '1:1081533382829:android:d3d771e0093b53e8a78624',
    messagingSenderId: '1081533382829',
    projectId: 'test-49143',
    storageBucket: 'test-49143.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT8krbbyEi1xA_iIdK8SBoeTvggvc-ZMo',
    appId: '1:1081533382829:ios:f136952ffcdd2986a78624',
    messagingSenderId: '1081533382829',
    projectId: 'test-49143',
    storageBucket: 'test-49143.firebasestorage.app',
    iosBundleId: 'com.lta.test.uwu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT8krbbyEi1xA_iIdK8SBoeTvggvc-ZMo',
    appId: '1:1081533382829:ios:f136952ffcdd2986a78624',
    messagingSenderId: '1081533382829',
    projectId: 'test-49143',
    storageBucket: 'test-49143.firebasestorage.app',
    iosBundleId: 'com.lta.test.uwu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAySrf8DKWQIx4oULMmDLhyZK4wP3cT0EY',
    appId: '1:1081533382829:web:06369166b542adafa78624',
    messagingSenderId: '1081533382829',
    projectId: 'test-49143',
    authDomain: 'test-49143.firebaseapp.com',
    storageBucket: 'test-49143.firebasestorage.app',
    measurementId: 'G-K7PEWGGBTF',
  );
}
